import product1 from "../assets/WaterPurifierImg.jpg";
import product2 from "../assets/WaterPurifierimg2.jpg";
import product3 from "../assets/WaterPurifierimg3.jpg";
import product4 from "../assets/WaterPurifierimg4.jpg";
import product5 from "../assets/WaterPurifierimg2.jpg";

const demoProducts = [
  {
    id: "1",
    name: "AquaPure RO Purifier",
    brandName: "AquaPure",
    buyingPrice: 120,
    sellingPrice: 150,
    vendorPrice: 100,
    quantity: 10,
    date: "2025-09-01",
    images: [product1],
    isTopSelling: true,
    isFeatured: false,
    isBudgetFriendly: true,
    customFields: [
      { name: "specialization", value: "Multispeciality RO system" },
      { name: "Capacity", value: "10 L" },
      { name: "Warranty", value: "6 Years" },
      { name: "Membrane Type", value: "Copper" },
      { name: "Power", value: "Rechargeable Battery" },
    ],
  },
  {
    id: "2",
    name: "HydroSmart UV Purifier",
    brandName: "HydroSmart",
    buyingPrice: 90,
    sellingPrice: 120,
    vendorPrice: 80,
    quantity: 5,
    date: "2025-09-02",
    images: [product2],
    isTopSelling: false,
    isFeatured: true,
    isBudgetFriendly: false,
    customFields: [
      { name: "specialization", value: "UV-based purifier" },
      { name: "Capacity", value: "8 L" },
      { name: "Warranty", value: "4 Years" },
      { name: "Membrane Type", value: "Carbon" },
      { name: "Power", value: "Direct Electric" },
    ],
  },
  {
    id: "3",
    name: "PureLife Copper+ RO",
    brandName: "PureLife",
    buyingPrice: 150,
    sellingPrice: 190,
    vendorPrice: 130,
    quantity: 8,
    date: "2025-09-03",
    images: [product3],
    isTopSelling: true,
    isFeatured: true,
    isBudgetFriendly: false,
    customFields: [
      { name: "specialization", value: "RO with Copper Infusion" },
      { name: "Capacity", value: "12 L" },
      { name: "Warranty", value: "5 Years" },
      { name: "Membrane Type", value: "RO + Copper" },
      { name: "Power", value: "Electric with Battery Backup" },
    ],
  },
  {
    id: "4",
    name: "EcoFresh Budget Purifier",
    brandName: "EcoFresh",
    buyingPrice: 70,
    sellingPrice: 100,
    vendorPrice: 60,
    quantity: 15,
    date: "2025-09-04",
    images: [product4],
    isTopSelling: false,
    isFeatured: false,
    isBudgetFriendly: true,
    customFields: [
      { name: "specialization", value: "Affordable RO + UV system" },
      { name: "Capacity", value: "7 L" },
      { name: "Warranty", value: "3 Years" },
      { name: "Membrane Type", value: "RO" },
      { name: "Power", value: "Direct Electric" },
    ],
  },
  {
    id: "5",
    name: "SmartHydra IoT Purifier",
    brandName: "SmartHydra",
    buyingPrice: 200,
    sellingPrice: 250,
    vendorPrice: 170,
    quantity: 6,
    date: "2025-09-05",
    images: [product5],
    isTopSelling: true,
    isFeatured: true,
    isBudgetFriendly: false,
    customFields: [
      { name: "specialization", value: "IoT-enabled smart purifier" },
      { name: "Capacity", value: "15 L" },
      { name: "Warranty", value: "7 Years" },
      { name: "Membrane Type", value: "Hybrid RO + UV" },
      { name: "Power", value: "Wi-Fi enabled, Electric" },
    ],
  },
];

export default demoProducts;
